page_title: novacard.ro
description: Novacard profile template_1
baseurl: "/" 
url: "https://template1.novacard.ro" 
avatar: 
name: Nova Card
title:
company:
email: contact@novacard.ro
phone:
website: 
facebook_url: https://www.facebook.com/novacard/           
linkedin_url: https://www.linkedin.com/company/novacard    
instagram_url: https://www.instagram.com/novacard/         
pinterest_url:                                            
twitter_url:                                        
youtube_url:                                               
snapchat_url:                                         
whatsapp_url:                                            
tiktok_url:                                               
telegram_url:                                           
skype_url:                                               
github_url:                                              
gitlab_url:                                             
markdown: kramdown