page_title: Coriolan Calotescu - novacard.ro
description: Novacard profile template_1
baseurl: "/" 
url: "https://template1.novacard.ro" 
avatar: "avatar.jpeg"
contact-first_name: Nova 
contact-last_name: Card
contact-title:
contact-company:
contact-email: contact@novacard.ro
contact-phone:
contact-website: 
contact-facebook_url: https://www.facebook.com/novacard/           
contact-linkedin_url: https://www.linkedin.com/company/novacard    
contact-instagram_url: https://www.instagram.com/novacard/         
contact-pinterest_url:                                            
contact-twitter_url:                                        
contact-youtube_url:                                               
contact-snapchat_url:                                         
contact-whatsapp_url:                                            
contact-tiktok_url:                                               
contact-telegram_url:                                           
contact-skype_url:                                               
contact-github_url:                                              
contact-gitlab_url:                                             
markdown: kramdown