page_title: Coriolan Calotescu - novacard.ro
description: Novacard profile - coriolancalotescu
baseurl: /
url: https://coriolancalotescu.novacard.ro
avatar: avatar.jpeg
contact-first_name: Coriolan
contact-last_name: Calotescu
contact-title: Director
contact-company: Diamond House Boutique
contact-email: 
contact-phone: +40745033585
contact-website: 
contact-facebook_url: https://www.facebook.com/coriolan.calotescu
contact-linkedin_url: 
contact-instagram_url: 
contact-pinterest_url: 
contact-twitter_url: 
contact-youtube_url: 
contact-snapchat_url: 
contact-whatsapp_url: 
contact-tiktok_url: 
contact-telegram_url: 
contact-skype_url: 
contact-github_url: 
contact-gitlab_url: 
