# Site settings
page_title: novacard.ro
description: Novacard profile template_1
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://template_1.novacard.ro" # the base hostname & protocol for your site


# Identity
name: Nova Card
title: 1
company: 1


# Contacts
email: contact@novacard.ro
phone: 1
website: 1 # https://your-website.ltd 


# Social settings
facebook_url: https://www.facebook.com/novacard/           # https://facebook.com/username/
linkedin_url: https://www.linkedin.com/company/novacard    # https://www.linkedin.com/in/username
instagram_url: https://www.instagram.com/novacard/         # https://www.instagram.com/username
pinterest_url: 1                                            # https://pinterest.com/username
twitter_url: 1                                              # https://twitter.com/username
youtube_url: 1                                              # https://youtube.com/channel/channel-id
snapchat_url: 1                                             # https://snapchat.com/add/
whatsapp_url: 1                                             # https://wa.me/your-phone-number-with-country-prefix
tiktok_urk: 1                                               # https://tiktok.com/@username
telegram_url: 1                                             # https://t.me/username
skype_url: 1                                                # https://join.skype.com/invite/user-id
github_url: 1                                               # https://github.com/username
gitlab_url: 1                                               # https://gitlab.com/username


# Build settings
markdown: kramdown
